# Site information
site_name: BurkimbIA
site_description: Technical documentation for your BurkimbIA initiative
repo_url: https://github.com/BurkimbIA/docs
repo_name: Docs
edit_uri: https://github.com/BurkimbIA/docs

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: green
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: lime
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - navigation.top
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - glightbox
  - search
  - git-revision-date-localized:
      type: iso_date
      fallback_to_build_date: true
  - literate-nav:
      nav_file: SUMMARY.md

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - meta
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - md_in_html
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

# Extra JavaScript for math support
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

